### ISSUE TITLE
Gemspec doesn't include hashie and oauth gems

### ISSUE THREAD

**Issue by bdotdub** [jeremyrwelch/Foursquare#1]
When installing the `foursquare` gem, it did not install the `hashie` and `oauth` gem. Added them to the gemspec here: http://github.com/bdotdub/Foursquare/commit/5ceff3819f77f268cf512548e6472ae10a1f377b

**Comment by tjhanley** [comment]
integrated your change list. thanks!

**Comment by mishawagon** [comment]
Hello,
This is still a problem I think. I had to manually require hashie and oauth in gemfile before requiring foursquare gem for it all to work...

**Comment by tjhanley** [comment]
I updated the gemspec and the version number. I don't have access to push the gem to rubygems. I've sent a message to Jeremy

**Comment by tjhanley** [comment]
I got access to the ruby-gems account. I just pushed an update to the gem with the requirements.

**Comment by bdotdub** [comment]
+1!
